import { DEFAULT_TAKE, INITIAL_SKIP } from '@react3l/react3l/config';
import { Model } from '@react3l/react3l/core/model';
import { Entity, Field } from '@react3l/react3l/decorators';
import { OrderType } from '@react3l/react3l/types';

/**
 * App model filter
 * - Each Model should have and only have one ModelFilter
 * - ModelFilters can be auto-generated by using CodeGenerator
 *
 * @package "react3l"
 * @author "thanhtunguet <ht@thanhtunguet.info>"
 * @module "react3l/core"
 * @class {ModelFilter}
 */
@Entity()
export class ModelFilter<T extends Model = Model> extends Model {
  /**
   * Skip number
   *
   * @type {number}
   */
  @Field(Number)
  public skip: number = INITIAL_SKIP;

  /**
   * Take number
   *
   * @type {number}
   */
  @Field(Number)
  public take: number = DEFAULT_TAKE;

  /**
   * Field name to order by
   *
   * @type {string}
   */
  @Field(String)
  public orderBy?: keyof T | string = null;

  /**
   * Order type
   *
   * @type {OrderType}
   */
  @Field(String)
  public orderType?: OrderType = null;

  /**
   * Filter fields
   */
  [key: string]: any;
}
