import {ErrorMap} from 'core/error-map';
import {TypeChecking} from 'helpers/type-checking';

/**
 * App model
 * - Each model should represent a table in database
 * - Models can be auto-generated by using CodeGenerator
 *
 * @package "react3l"
 * @author "thanhtunguet <ht@thanhtunguet.info>"
 * @module "react3l/core"
 * @class {Model}
 */
export class Model {
  /**
   * Clone a model instance
   *
   * @param {Partial<T>} partial
   * @return {Model}
   */
  public static clone<T>(partial: Partial<T>) {
    const instance = new this();
    if (TypeChecking.isObject(partial)) {
      Object.assign(instance, partial);
    }
    return instance;
  }

  /**
   * Backend validation errors
   *
   * @type {ErrorMap<self>}
   */
  public errors?: ErrorMap<this>;

  /**
   * Model fields
   *
   * @type {any}
   */
  [key: string]: any;
}
